action_edge : [[0,1],[1,0],
            [1,2],[2,1],
            [0,2],[2,0], #e4Acc

            [3,4],[4,3],
            [3,5],[5,3],
            [4,5],[5,4], #mAcc

            [6,7],[7,6],
            [6,8],[8,6],
            [7,8],[8,7], #mGyr (x,y,z)

            [9,10],[10,9],
            [9,11],[11,9],
            [10,11],[11,10], #mGyr (roll,pitch,yaw)

            [12,13],[13,12],
            [12,14],[14,12],
            [13,14],[14,13], #mMag
            
            [0,3],[3,0],
            [0,6],[6,0],
            [0,9],[9,0],
            [0,12],[12,0],
            [3,6],[6,3],
            [3,9], [9,3],
            [3,12],[3,12],
            [6,9],[9,6],
            [6,12],[12,6], #x

            [1,4],[4,1],
            [1,7],[7,1],
            [1,13],[13,1],
            [4,7],[7,4],
            [4,13],[13,4],
            [7,13],[13,7], #y
           
            [2,5],[5,2],
            [2,8],[8,2],
            [2,14],[14,2],
            [5,8],[8,5],
            [5,14],[14,5],
            [8,14],[14,8] #z
            ]

body_edge : [[0,1],[1,0],
            [0,2],[2,0],
            [0,3],[3,0],
            [1,2],[2,1],
            [1,3],[3,1],
            [2,3],[3,2]]
            
action_nodes : 15
action_kernel_size : 5 #200
action_gnn_outputdim : 64
body_nodes : 4
body_kernel_size : 3 #30
body_gnn_outputdim : 64
# fft_dim : 1501
classes : 16
